require: rubocop-rspec

inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 120
  
# 対象外
AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**"
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - "node_modules/**/*"
    - "tmp/**/*"
    - "lib/**/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.6.3
